### PR TITLE
#159236216 Enable social logins

### PR DESCRIPTION
**Pull request by solnsubuga**
#### What does this PR do?
This PR allows a user to login with their pre-existing social media account.
#### Description of Task to be completed?
- Enable login with facebook, twitter and google.
#### How should this be manually tested?
- Pull the branch `ft-enable-social-logins-159236216`
- Install requirements `pip install -r requirements.txt`
- set the following environment variables `SOCIAL_AUTH_FACEBOOK_KEY` `SOCIAL_AUTH_FACEBOOK_SECRET` `SOCIAL_AUTH_TWITTER_KEY` `SOCIAL_AUTH_TWITTER_SECRET` `SOCIAL_AUTH_GOOGLE_OAUTH2_SECRET` `SOCIAL_AUTH_GOOGLE_OAUTH2_KEY` Note these will be shared for development.
- Run migrations `python manage.py migrate`
- Run the app `python manage.py runserver` and ensure to use `localhost:8000` and not `127.0.0.1:8000` Please note the port must be `8000`
- The facebook account to use to test must be specified, currently only my facebook can be used looking for a way I can add team's accounts 
#### What are the relevant pivotal tracker stories?
[#159236216](https://www.pivotaltracker.com/story/show/159236216)
#### Screenshots (if appropriate)
screen shot 2018-08-02 at 12 23 09
screen shot 2018-08-01 at 15 41 34
screen shot 2018-08-01 at 15 42 06

### CODE REVIEW

**Comment by wasswa-derick** [comment]
@solnsubuga 
I would like to have the authentication keys (for facebook, twitter, and google) you used so that I can set them in my environment and be able to review this PR. thanks.

`SOCIAL_AUTH_FACEBOOK_KEY = os.environ.get('SOCIAL_AUTH_FACEBOOK_KEY')`

**Comment by wasswa-derick** [comment]
@solnsubuga 
Twitter Login, Facebook and Google Login Work perfectly.

**Comment by wasswa-derick** [comment]
Though I have a little suggestion on the UI. I would suggest that the social login buttons be centered and some space is added from the wger login button.
We could deliberate about this and get a consensus.

screen shot 2018-08-02 at 11 14 59

**Comment by Yiga-fred** [comment]
@solnsubuga  the all the logins work fine, but I also recommend a rework on the buttons alignment. Good work.

**Comment by lym** [comment]
@solnsubuga Please center-align the buttons like @wasswa-derick suggests. It will be more aesthetically pleasing.

**Comment by RrNn** [comment]
@solnsubuga I think you need to center the buttons also, because even the first twitter button is actually overly to the left and is not aligned with the `login` button.

**Comment by solnsubuga** [comment]
@wasswa-derick @Yiga-fred @lym I have centred the buttons.

**Pull request merged**
