### PR TITLE
Update muscle and exercise lists

### PR DESCRIPTION
**Pull request by wasswa-derick**
#### What does this PR do?
* Add new muscles and exercises to the muscle and exercise lists.

#### Description of Task to be completed?
* Add muscles to the muscle list.
* Create the skeletal representations for the new muscles. 
* Map the muscles to the available exercises.
* Add new exercises for the new muscles.

#### How should this be manually tested?
* Clone the project, ```https://github.com/andela/wg-wits.git```.
* In your terminal, ```cd wg-wits```
* Checkout to the ```ft-update-muscle-list-159236208``` branch.
* In the project directory, create a virtual environment and activate it: run ```virtualenv -p python3 venv-django``` then ```source venv-django/bin/activate```
* Install requirements ```pip install -r requirements_devel.txt```
* Load the fixtures to add the muscles and exercises data in the database with ```invoke load-fixtures```
* Serve the application ```python manage.py runserver```
* In the browser, visit ```http://127.0.0.1:8000/en/exercise/muscle/overview/``` to see the new muscles (Look out for `Forearms`, `Lateral deltoids`, and `Posterious Deltoid`).
* In the browser, visit ```http://127.0.0.1:8000/en/exercise/overview/``` to see the new exercises (Look out for `Behind-the-Back Cable Curl`, `Wide Grip Curl`, `Towel Cable Row`, `Towel Pullup`, `Crab Walk`, `Parallel Bar Hand Walk`,` Chinup`, `Reverse Overhead Laterals and Rear Military Press`).

#### What are the relevant pivotal tracker stories?
[#159236208](https://www.pivotaltracker.com/story/show/159236208)

#### Screenshots (if appropriate)

* **Forearms muscle**

screen shot 2018-08-22 at 13 06 06

* **Lateral Deltoid muscle**

screen shot 2018-08-22 at 13 06 22

* **Posterior Deltoid muscle**

screen shot 2018-08-22 at 13 06 36

* **Exercises** 

screen shot 2018-08-22 at 16 30 26

screen shot 2018-08-22 at 16 31 07

screen shot 2018-08-22 at 16 31 28

screen shot 2018-08-22 at 16 31 49

### CODE REVIEW

**Comment by RrNn** [comment]
LGTM.
Everything is as said in the description. Good work @wasswa-derick

**Review by solnsubuga — APPROVED** [review]
Looks good.

**Review by Yiga-fred — APPROVED** [review]
LGTM

**Review by RrNn — APPROVED** [review]
LGTM.
Everything is as said in the description. Good work @wasswa-derick
You could add another screenshot for the `http://127.0.0.1:8000/en/exercise/overview/` endpoint though

**Pull request merged**
