### PR TITLE
#159236193 Rework landing page

### PR DESCRIPTION
**Pull request by wasswa-derick**
#### What does this PR do?
* Redesigns the Landing page to give it more value.

#### Description of Task to be completed?
* Make a rework on the landing page so that a user understands the features provided by wger before scrolling.
* Make the landing page appealing to both males and females

#### How should this be manually tested?
* Clone the project, ```https://github.com/andela/wg-wits.git```.
* In your terminal, ```cd wg-wits```
* Checkout to the ft-landing-page-rework-159236193 branch.
* In the project directory, create a virtual environment and activate it: run  ```virtualenv -p python3 venv-django``` then ```source venv-django/bin/activate```
* Install requirements ```pip install -r requirements_devel.txt```
* Serve the application ```python manage.py runserver```
* In the browser, visit, ```http://127.0.0.1:8000/en/software/features```
* The Landing Page you see should look the screenshots shared below.

#### Any background context you want to provide?
* The background Image was changed because the current image was more masculine and the case here is to make it more appealing to both males and females.
#### What are the relevant pivotal tracker stories?
[#159236193](https://www.pivotaltracker.com/story/show/159236215)

#### Screenshots (if appropriate)

Re-designed Landing Pages
screen shot 2018-08-01 at 08 38 31

screen shot 2018-08-01 at 08 38 59

### CODE REVIEW

**Comment by Yiga-fred** [comment]
@wasswa-derick I have checked out your work but first, of all, there's an error on how a reviewer can install requirements **pip install requirements_devel.txt** it should be **pip install -r requirements_devel.txt** and also I have had to click to see what wger offers, is it possible for you to make the features hover one by one?

**Comment by wasswa-derick** [comment]
@Yiga-fred 
Lemme resolve that.

**Comment by RrNn** [comment]
@wasswa-derick , the carousel is fine. At least much of the info about Wger can be seen,  rather than the previous need to scroll but fix the build fails

**Comment by ja-odur** [comment]
@wasswa-derick,
I tested the PR. It ran as expected with all tests passing but you need to look at the test coverage.

**Pull request merged**
